/**
 * The coldroom meter register — the file that retires the RM0.484 back-inference.
 *
 * `tests/fixtures/coldroom-register.json` is generated by running the real
 * parser over the real extract of E-2026.xls, so a failure here is a change in
 * behaviour rather than a change in what somebody typed. The sha256 of the
 * source workbook is carried with it: if the owner sends a new copy, the
 * fixture has to be regenerated deliberately rather than drifting.
 *
 * What is worth testing here is not the arithmetic — subtraction is not in
 * doubt — but the three judgements the register forced:
 *
 *   1. Rows are keyed by POSITION, not by room code. Two different rooms are
 *      both called D5, and a room re-let mid-month appears twice.
 *   2. Own use follows the OCCUPANT, not the room number. The owner's cost
 *      template used the room number and charged a tenant's ice to the plant.
 *   3. A register beats a whole-room meter beats a ringgit back-inference, and
 *      the report has to say which one it used.
 */
import { describe, it, expect } from 'vitest'
import { coldroomSplit, type ColdroomRegisterRow } from '@/lib/site-energy'
import { isOwnUseTenant, CONVENTIONAL_OWN_USE_ROOMS } from '@/lib/import/parsers'
import { carryForward } from '@/lib/coldroom-entry'
import { validateRegister, validateRegisterRow, hasBlocking, isOwnUseLabel } from '@/lib/validation'
import fixture from './fixtures/coldroom-register.json'

const LEGACY = '0.484'
const TENANT = '0.543'

const row = (over: Partial<ColdroomRegisterRow> = {}): ColdroomRegisterRow => ({
  roomCode: 'A1',
  tenantLabel: 'Someone',
  ownUse: false,
  openingKwh: '1000',
  closingKwh: '1100',
  ...over,
})

describe('who counts as KFI', () => {
  it.each([
    ['KFI', true],
    ['kfi', true],
    ['KFI ', true],
    ['KFI Cold Storage', true],
    ['Permatang Chengai', false],
    ['Zaidah Ibrahim (start 10/2/26 - 9/3/26)', false],
    ['', false],
    [null, false],
    // The one that would bite: a tenant whose name merely begins with the
    // letters. \b stops "KFIX Trading" matching, which a bare prefix test would.
    ['KFIX Trading', false],
  ])('reads %s as own use = %s', (label, expected) => {
    expect(isOwnUseTenant(label)).toBe(expected)
  })
})

describe('the register outranks every other source', () => {
  const register = [
    row({ roomCode: 'D10', tenantLabel: 'KFI', ownUse: true, openingKwh: '0', closingKwh: '3000' }),
    row({ roomCode: 'B1', openingKwh: '0', closingKwh: '5000' }),
  ]

  it('uses the register even when a whole-room meter is also present', () => {
    const split = coldroomSplit(
      { register, meteredKwh: '99999', ratonoRm: '48400', yemintRm: '0', iceStoreInvoicedRm: '5430' },
      LEGACY,
      TENANT
    )
    expect(split.provenance).toBe('REGISTER')
    expect(split.totalKwh.toString()).toBe('8000')
    expect(split.iceStoreKwh.toString()).toBe('3000')
    expect(split.tenantKwh.toString()).toBe('5000')
    expect(split.source).toBe('METERED')
    expect(split.backInferred).toBe(false)
    expect(split.roomCount).toBe(2)
  })

  it('names the rooms KFI occupied rather than a fixed list', () => {
    const split = coldroomSplit({ register }, LEGACY, TENANT)
    expect(split.iceStoreBasis).toContain('D10')
    expect(split.totalBasis).toContain('2 rooms read')
  })

  it('falls back to the whole-room meter, then to the back-inference', () => {
    const metered = coldroomSplit({ meteredKwh: '50000', iceStoreInvoicedRm: '5430' }, LEGACY, TENANT)
    expect(metered.provenance).toBe('WHOLE_METER')
    expect(metered.backInferred).toBe(false)

    const inferred = coldroomSplit({ ratonoRm: '48400', iceStoreInvoicedRm: '5430' }, LEGACY, TENANT)
    expect(inferred.provenance).toBe('BACK_INFERRED')
    expect(inferred.backInferred).toBe(true)
    expect(inferred.totalBasis).toContain('BACK-INFERRED')
  })

  it('does not treat an empty register as a register', () => {
    // An empty array means "no rows loaded", not "the coldroom used nothing".
    // Falling through to the next source is the only safe reading.
    const split = coldroomSplit({ register: [], meteredKwh: '50000' }, LEGACY, TENANT)
    expect(split.provenance).toBe('WHOLE_METER')
  })

  it('reports a month where KFI occupied nothing, without pretending otherwise', () => {
    const split = coldroomSplit({ register: [row({ openingKwh: '0', closingKwh: '900' })] }, LEGACY, TENANT)
    expect(split.iceStoreKwh.toString()).toBe('0')
    expect(split.tenantKwh.toString()).toBe('900')
    expect(split.iceStoreBasis).toContain('no room occupied by KFI')
  })
})

describe('the real register, month by month', () => {
  it('carries the sha256 of the workbook it came from', () => {
    expect(fixture.sourceSha256).toMatch(/^[0-9a-f]{64}$/)
  })

  it('covers December 2025 to August 2026', () => {
    expect(fixture.months.map((m) => m.month)).toEqual([
      '2025-12', '2026-01', '2026-02', '2026-03',
      '2026-04', '2026-05', '2026-06', '2026-07', '2026-08',
    ])
  })

  it.each(fixture.months.map((m) => [m.month, m] as const))(
    'splits %s the same way the engine does',
    (_month, m) => {
      const split = coldroomSplit(
        {
          register: [
            { roomCode: 'OWN', ownUse: true, openingKwh: 0, closingKwh: m.ownUseKwh },
            { roomCode: 'LET', ownUse: false, openingKwh: 0, closingKwh: m.totalKwh - m.ownUseKwh },
          ],
        },
        LEGACY,
        TENANT
      )
      expect(split.totalKwh.toNumber()).toBe(m.totalKwh)
      expect(split.iceStoreKwh.toNumber()).toBe(m.ownUseKwh)
      expect(split.tenantKwh.toNumber()).toBe(m.totalKwh - m.ownUseKwh)
    }
  )

  it('agrees with the owner’s cost template on every month it also covers', () => {
    // The template back-inferred these by dividing its ringgit compilations by
    // RM0.484/kWh. That the two agree to the kWh is not luck: the compilations
    // were struck FROM these readings at that rate, so dividing back out was
    // exactly invertible. It was never a measurement, though — see the split below.
    const template: Record<string, number> = {
      '2026-01': 53297, '2026-02': 53797, '2026-03': 62489,
      '2026-04': 53980, '2026-05': 58481, '2026-06': 55035,
    }
    for (const m of fixture.months) {
      if (!(m.month in template)) continue
      expect(m.totalKwh, `${m.month} total`).toBe(template[m.month])
    }
  })

  it('keeps every row of a month with duplicated room codes', () => {
    // 29 rooms in a normal month; the count moves as tenants come and go, and
    // as a room is re-let part-way through. Keying on the room code would have
    // silently dropped one row of each duplicated pair.
    const dec = fixture.months.find((m) => m.month === '2025-12')!
    expect(dec.duplicatedRoomCodes).toContain('D5')
    expect(dec.rooms).toBe(29)

    const mar = fixture.months.find((m) => m.month === '2026-03')!
    expect(mar.rooms).toBe(31)
    expect(mar.duplicatedRoomCodes).toEqual(['C4', 'D12', 'D5'])
  })
})

describe('March 2026, where the room number and the occupant part company', () => {
  const march = fixture.march
  const mar = fixture.months.find((m) => m.month === '2026-03')!

  it('shows D12 let to a tenant for most of the month', () => {
    const d12 = march.filter((r) => r.roomCode === 'D12')
    expect(d12).toHaveLength(2)
    const letOut = d12.find((r) => !r.ownUse)!
    const kept = d12.find((r) => r.ownUse)!
    expect(letOut.tenantLabel).toMatch(/Zaidah/)
    expect(letOut.kwh).toBe(1653)
    expect(kept.kwh).toBe(76)
    // The register runs continuously across the handover: the tenant's closing
    // IS KFI's opening. That is what makes this a real split of one meter
    // rather than two rows that happen to share a label — and it is why both
    // rows can be trusted rather than one being a duplicate to discard.
    expect(kept.openingKwh).toBe(letOut.closingKwh)
    expect(letOut.kwh + kept.kwh).toBe(kept.closingKwh - letOut.openingKwh)
  })

  it('charges the tenant’s consumption to the tenant, not to cost of ice', () => {
    expect(mar.ownUseKwh).toBe(6140)
    expect(mar.byRoomCodeKwh).toBe(7793)
    // What the owner's template actually put in its ice-storage line.
    const templateIceStore = 7717
    expect(templateIceStore - mar.ownUseKwh).toBe(1577)
  })

  it('is the only month where the two rules disagree materially', () => {
    const diverging = fixture.months.filter((m) => m.ownUseKwh !== m.byRoomCodeKwh)
    expect(diverging.map((m) => m.month)).toEqual(['2026-03'])
  })

  it('still lists D10-D12 as the conventional rooms, for the report to argue with', () => {
    expect(CONVENTIONAL_OWN_USE_ROOMS).toEqual(['D10', 'D11', 'D12'])
  })
})

describe('what the register says about the coldroom business', () => {
  it('shows tenant consumption dwarfing KFI’s own', () => {
    for (const m of fixture.months) {
      const tenant = m.totalKwh - m.ownUseKwh
      expect(tenant, `${m.month}`).toBeGreaterThan(m.ownUseKwh * 5)
    }
  })

  it('never produces a negative tenant figure', () => {
    for (const m of fixture.months) {
      expect(m.totalKwh - m.ownUseKwh, `${m.month}`).toBeGreaterThan(0)
    }
  })

  it('reads December 2025 despite its shifted columns', () => {
    // dec25 carries an extra "Inv No" column, so its meters sit at D/E where
    // every other sheet has C/D. The parser finds columns by label; a
    // positional map would have read the tenant column as a meter.
    const dec = fixture.december
    expect(dec.length).toBeGreaterThan(0)
    for (const r of dec) {
      expect(Number(r.rateRmPerKwh)).toBe(0.543)
      expect(Number.isFinite(Number(r.openingKwh))).toBe(true)
      expect(Number(r.closingKwh)).toBeGreaterThanOrEqual(Number(r.openingKwh))
    }
  })
})

describe('keying next month: what carries forward', () => {
  const r = (rowNo: number, roomCode: string, openingKwh: number, closingKwh: number) => ({
    rowNo, roomCode, openingKwh, closingKwh,
  })

  it('carries one row per room in the ordinary case', () => {
    const out = carryForward([r(1, 'A1', 100, 150), r(2, 'B1', 200, 260)])
    expect(out.map((x) => x.roomCode)).toEqual(['A1', 'B1'])
  })

  it('collapses a room re-let mid-month to its final closing', () => {
    // March's D12: a tenant to 610,404, then KFI from 610,404. One meter, read
    // twice. Next month starts from where it ended, not from the handover.
    const out = carryForward([
      r(30, 'D12', 608_751, 610_404),
      r(31, 'D12', 610_404, 610_480),
    ])
    expect(out).toHaveLength(1)
    expect(out[0].closingKwh).toBe(610_480)
  })

  it('keeps BOTH rooms when one label covers two different meters', () => {
    // The bug this test exists for: collapsing by room code dropped one of the
    // two D5 rooms, and next month it silently stopped being read.
    const out = carryForward([
      r(22, 'D5', 564_767, 564_767),
      r(23, 'D5', 486_831, 486_831),
    ])
    expect(out).toHaveLength(2)
    expect(out.map((x) => x.openingKwh).sort()).toEqual([486_831, 564_767])
  })

  it('handles a room both re-let AND duplicated, without losing either meter', () => {
    const out = carryForward([
      r(1, 'D5', 564_767, 564_900),
      r(2, 'D5', 564_900, 565_000), // continues the first meter
      r(3, 'D5', 486_831, 486_900), // a different meter entirely
    ])
    expect(out).toHaveLength(2)
    expect(out.map((x) => x.closingKwh).sort()).toEqual([486_900, 565_000])
  })

  it('preserves the register order so the screen reads like the sheet', () => {
    const out = carryForward([r(3, 'C1', 1, 2), r(1, 'A1', 1, 2), r(2, 'B1', 1, 2)])
    expect(out.map((x) => x.roomCode)).toEqual(['A1', 'B1', 'C1'])
  })
})

describe('keying next month: what the validation refuses', () => {
  const base = {
    rowNo: 1, roomCode: 'B1', tenantLabel: 'Shabila Enterprise', ownUse: false,
    openingKwh: '1000', closingKwh: '1100', rateRmPerKwh: '0.5430',
  }

  it('accepts an ordinary row', () => {
    expect(validateRegisterRow(base)).toHaveLength(0)
  })

  it('treats a row with no closing as unfinished, not as an error', () => {
    // Mid-entry blanks are normal on a screen with thirty rooms.
    expect(validateRegisterRow({ ...base, closingKwh: null })).toHaveLength(0)
  })

  it('refuses a closing below the opening', () => {
    const issues = validateRegisterRow({ ...base, closingKwh: '900' })
    expect(hasBlocking(issues)).toBe(true)
    expect(issues[0].message).toMatch(/meter replaced/)
  })

  it('allows it once the meter is declared replaced, and asks for a note', () => {
    // A2 in January 2026: the register was swapped, December closed at 96,670
    // and January opened at 799.
    const issues = validateRegisterRow({
      ...base, openingKwh: '96670', closingKwh: '799', meterReplaced: true,
    })
    expect(hasBlocking(issues)).toBe(false)
    expect(issues[0].requiresNote).toBe(true)
  })

  it('warns when the chain no longer joins last month', () => {
    const forward = validateRegisterRow({ ...base, openingKwh: '1050', priorClosing: '1000' })
    expect(hasBlocking(forward)).toBe(false)
    expect(forward[0].message).toMatch(/not recorded anywhere/)

    const backward = validateRegisterRow({ ...base, openingKwh: '950', priorClosing: '1000' })
    expect(backward[0].message).toMatch(/already billed last month/)
  })

  it('warns when the own-use flag and the occupant disagree', () => {
    const notFlagged = validateRegisterRow({ ...base, tenantLabel: 'KFI', ownUse: false })
    expect(notFlagged.some((i) => i.message.includes('recharged to a tenant'))).toBe(true)

    const overFlagged = validateRegisterRow({ ...base, tenantLabel: 'RB meat', ownUse: true })
    expect(overFlagged.some((i) => i.message.includes('cost of ice'))).toBe(true)
    // Neither blocks: the office can overrule, and March 2026 is why.
    expect(hasBlocking([...notFlagged, ...overFlagged])).toBe(false)
  })

  it('refuses a row with no rate', () => {
    expect(hasBlocking(validateRegisterRow({ ...base, rateRmPerKwh: null }))).toBe(true)
  })

  it('refuses two rows reading one room from the same opening', () => {
    // A genuine mid-month split runs continuously. Two rows from one opening is
    // a duplicated row, and it would double-count the room.
    const issues = validateRegister([
      { ...base, rowNo: 1, roomCode: 'D12', openingKwh: '1000', closingKwh: '1100' },
      { ...base, rowNo: 2, roomCode: 'D12', openingKwh: '1000', closingKwh: '1200' },
    ])
    expect(hasBlocking(issues)).toBe(true)
    expect(issues.find((i) => i.message.includes('duplicated row'))).toBeTruthy()
  })

  it('accepts a genuine mid-month split', () => {
    const issues = validateRegister([
      { ...base, rowNo: 1, roomCode: 'D12', openingKwh: '608751', closingKwh: '610404' },
      { ...base, rowNo: 2, roomCode: 'D12', tenantLabel: 'KFI', ownUse: true,
        openingKwh: '610404', closingKwh: '610480' },
    ])
    expect(hasBlocking(issues)).toBe(false)
  })

  it('warns rather than silently emptying the month when nothing is keyed', () => {
    const issues = validateRegister([{ ...base, closingKwh: null }])
    expect(hasBlocking(issues)).toBe(false)
    expect(issues[0].message).toMatch(/falls back to the ringgit compilations/)
  })

  it('warns when no room is marked as KFI’s own', () => {
    const issues = validateRegister([base])
    expect(issues.some((i) => i.message.includes('none of the coldroom will be costed to ice')))
      .toBe(true)
  })
})

describe('the two copies of the own-use rule agree', () => {
  // `isOwnUseLabel` in validation.ts is deliberately duplicated from
  // `isOwnUseTenant` in the importer, so the browser bundle does not drag in the
  // workbook types. Duplication is only safe while something checks it.
  it.each([
    'KFI', 'kfi', 'KFI Cold Storage', 'KFIX Trading', 'RB meat', '', null,
  ])('agrees on %s', (label) => {
    expect(isOwnUseLabel(label)).toBe(isOwnUseTenant(label))
  })
})

describe('where this system deliberately departs from the workbook', () => {
  // The adversarial audit killed a claim worth recording the death of. The
  // workbook does NOT identify KFI's own use by the tenant column: every sheet
  // carries a "Less : Own Use" footer labelled by LOT CODE — LOT D10, LOT D11,
  // LOT D12 — and resolves those labels POSITIONALLY. In March 2026 the cell
  // labelled "LOT D12" points at the Zaidah Ibrahim row, and the row whose
  // tenant column actually reads KFI is referenced by nothing.
  //
  // So the occupant rule is this system's decision, not the workbook's, and it
  // disagrees with the workbook in exactly one month. That is worth pinning:
  // a future reader finding the difference should see it was chosen.
  it('agrees with the workbook’s own footer on eight of the nine months', () => {
    const agreeing = fixture.months.filter((m) => m.ownUseKwh === m.sheetOwnUseKwh)
    expect(agreeing).toHaveLength(8)
  })

  it('differs in March, and only in March, by the tenant’s consumption', () => {
    const differing = fixture.months.filter((m) => m.ownUseKwh !== m.sheetOwnUseKwh)
    expect(differing.map((m) => m.month)).toEqual(['2026-03'])
    const mar = differing[0]
    expect(mar.sheetOwnUseKwh - mar.ownUseKwh).toBe(1577)
    // At the tenant rate this is what was mis-recharged; at the site blended
    // rate it is what reached cost of ice. Both matter, to different people.
    expect(Math.round((mar.sheetOwnUseKwh - mar.ownUseKwh) * fixture.tenantRate)).toBe(856)
  })

  it('shows the footer is hand-maintained rather than derived', () => {
    // December's block has FOUR lines, one of them a room with no tenant at all
    // (A3, at RM0.00) and one of them mistyped as "LOT 11" for D11. A block
    // that can be mistyped is a block that can point at the wrong row — which
    // is precisely what it does in March.
    const dec = fixture.months.find((m) => m.month === '2025-12')!
    expect(dec.sheetOwnUseLines).toEqual(['LOT A3', 'LOT D12', 'LOT 11', 'LOT D10'])
    // It still totals correctly, because the extra line is zero.
    expect(dec.sheetOwnUseKwh).toBe(dec.ownUseKwh)
  })
})
